---
apiVersion: v1
kind: Namespace
metadata:
  name: mariadb
---
apiVersion: apps.open-cluster-management.io/v1
kind: Channel
metadata:
  name: mariadb-app
  namespace: mariadb
spec:
  type: Git
  pathname: https://github.com/michaelkotelnikov/rhacm-demo.git
---
apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: dev-clusters
  namespace: mariadb
spec:
  clusterConditions:
    - type: ManagedClusterConditionAvailable
      status: "True"
  clusterSelector:
    matchLabels:
      name: punemgmt
---
apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  name: mariadb-app
  namespace: mariadb
  labels:
    app: mariadb-app
  annotations:
    apps.open-cluster-management.io/github-path: mariadb-resources
spec:
  channel: mariadb/mariadb-app
    config:
    env:
    - name: HTTP_PROXY
      value: 'http://10.68.248.34:80'
    - name: HTTPS_PROXY
      value: 'http://10.68.248.34:80'
    - name: NO_PROXY
      value: >-
        localhost,bastion.mgmt.infyitapps.local,bastion.cloud.infyitapps.local,api.mgmt.infyitapps.local,api.cloud.infyitapps.local,10.174.114.72,10.174.114.73,10.174.114.74,10.174.114.75,10.174.114.76,quay-registry-quay-quay-registry.apps.mgmt.infyitapps.local,api.mgmt.infyitapps.local,api-int.mgmt.infyitapps.local,api-int.cloud.infyitapps.local,.mgmt.infyitapps.local,.cloud.infyitapps.local,.infyitapps.local,.svc.cluster.local,.svc,.apps.mgmt.infyitapps.local,.apps.cloud.infyitapps.local,central-stackrox.apps.mgmt.infyitapps.local,console-openshift-console.apps.mgmt.infyitapps.local,console-openshift-console.apps.cloud.infyitapps.local,172.30.0.0/16,10.128.0.0/14,10.174.114.64/26,10.174.210.0/23
  placement:
    placementRef:
      kind: PlacementRule
      name: dev-clusters
---
apiVersion: app.k8s.io/v1beta1
kind: Application
metadata:
  name: mariadb-app
  namespace: mariadb
spec:
  componentKinds:
  - group: apps.open-cluster-management.io
    kind: Subscription
  descriptor: {}
  selector:
    matchExpressions:
    - key: app
      operator: In
      values:
      - mariadb-app
